name: 'Deploy'
description: 'Chooses with Heroku app to target based on the branch'
inputs:
  heroku-review1:
    description: 'Heroku review1 app'
    required: true
  heroku-review2:
    description: 'Heroku review2 app'
    required: true
  heroku-review3:
    description: 'Heroku review3 app'
    required: true
  heroku-staging:
    description: 'Heroku staging app'
    required: true
  heroku-production:
    description: 'Heroku production app'
    required: true
outputs:
  heroku-app:
    description: 'Selected heroku app'
runs:
  using: 'node12'
  main: 'dist/index.js'