name: Deploy Manualpay

env:
  NODE_VERSION: 12.16.x

on:
  push:
    branches:
      - review1
      - review2
      - review3
      - master
      - release

jobs:
  deploy-server:
    name: "Deploy Server"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: selector
        name: 'Select target app'
        uses: ./.github/actions/app-selector
        with:
          heroku-review1: ${{ secrets.HEROKU_REVIEW1_APP }}
          heroku-review2: ${{ secrets.HEROKU_REVIEW2_APP }}
          heroku-review3: ${{ secrets.HEROKU_REVIEW3_APP }}
          heroku-staging: ${{ secrets.HEROKU_STAGING_APP }}
          heroku-production: ${{ secrets.HEROKU_PRODUCTION_APP }}
      - name: 'Deploy manualpay'
        run: |
          git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ steps.selector.outputs.heroku-app }}.git ${{ github.ref }}:master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

